name: 🔂 RunParsersToday

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5"
    - cron: "0 8-10 * * 1"
concurrency:
  group: parsers-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generateXMLFeedsToday:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # - run: sudo locale-gen de_DE.UTF-8
      # - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: git config
        run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull --ff-only
      - name: Run parsers & update xml feeds
        run: |
          python main.py
      - name: git commit & push
        run: |
          git add .
          # Use "|| true" or "--allow-empty"  otherwise the action fails for empty commits
          git commit -m "Update xml feeds" || true
          git push
